# Generated by Django 5.0.13 on 2025-04-27 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_keyvalue'),
    ]

    operations = [
        migrations.RenameField(
            model_name='keyvalue',
            old_name='raw_html',
            new_name='html',
        ),
    ]
