# Generated by Django 5.0.13 on 2025-08-20 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_education_experience_projects_testimonial_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testimonial',
            old_name='content',
            new_name='message',
        ),
    ]
