# Generated by Django 5.0.13 on 2025-08-20 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_content_testimonial_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='photo_ext',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='company',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='photo',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
