# Generated by Django 5.0.13 on 2025-08-20 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_testimonial_photo_ext_alter_testimonial_company_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonial',
            name='created_at',
        ),
        migrations.AddField(
            model_name='testimonial',
            name='disabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
