# Generated by Django 5.0.13 on 2025-08-20 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_testimonial_created_at_testimonial_disabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='favourites',
            field=models.BooleanField(default=False),
        ),
    ]
