# Generated by Django 5.0.13 on 2025-08-26 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_skills_experienceskillsmap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='end',
            field=models.CharField(default='PRESENT', max_length=100),
        ),
        migrations.CreateModel(
            name='ProjectStack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stack', models.CharField(max_length=100)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.projects')),
            ],
        ),
    ]
