# Generated by Django 5.0.13 on 2025-08-26 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_education_end_projectstack'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
