# Generated by Django 5.0.13 on 2025-08-29 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_projects_summary_alter_projects_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='image',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='image_ext',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='image_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
