# Generated by Django 5.0.13 on 2025-08-30 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_projects_image_projects_image_ext_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
