# Generated by Django 5.0.13 on 2025-08-30 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_projects_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='photo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
