# Generated by Django 5.0.13 on 2025-08-30 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_testimonial_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='end',
            field=models.CharField(default='PRESENT', max_length=100),
        ),
    ]
