# Generated by Django 5.0.13 on 2025-08-31 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_experience_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyvalue',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
